"""initial_schema

Revision ID: 066f128c18b4
Revises: 
Create Date: 2026-06-30 10:41:34.576846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066f128c18b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('participants', app.database.types.JSON(), nullable=False),
    sa.Column('metadata_', app.database.types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_table('provider',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key', app.database.types.EncryptedString(length=512), nullable=True),
    sa.Column('capabilities', app.database.types.JSON(), nullable=True),
    sa.Column('models', app.database.types.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider'))
    )
    op.create_table('tool',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=30), nullable=False),
    sa.Column('parameters', app.database.types.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_tool'))
    )
    op.create_table('attachment',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_attachment_conversation_id_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_index(op.f('ix_attachment_conversation_id'), 'attachment', ['conversation_id'], unique=False)
    op.create_table('message',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', app.database.types.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_', app.database.types.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], name=op.f('fk_message_parent_id_message'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index('ix_message_conversation_created', 'message', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_table('usage',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens_details', app.database.types.JSON(), nullable=True),
    sa.Column('completion_tokens_details', app.database.types.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_usage_message_id_message'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage'))
    )
    op.create_index(op.f('ix_usage_message_id'), 'usage', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_message_id'), table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_index('ix_message_conversation_created', table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_attachment_conversation_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_table('tool')
    op.drop_table('provider')
    op.drop_table('conversation')
    # ### end Alembic commands ###
