"""add plugin tables

Revision ID: 8f8b9ac4ea3b
Revises: 066f128c18b4
Create Date: 2026-06-30 15:15:57.048710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types  # noqa: F401 — used by autogenerate for custom types


# revision identifiers, used by Alembic.
revision: str = '8f8b9ac4ea3b'
down_revision: Union[str, Sequence[str], None] = '066f128c18b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('sdk_version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('homepage', sa.String(length=512), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('trust_tier', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('install_type', sa.String(length=20), nullable=False),
    sa.Column('entry_point', sa.String(length=255), nullable=True),
    sa.Column('manifest_path', sa.String(length=512), nullable=True),
    sa.Column('install_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin')),
    sa.UniqueConstraint('name', name=op.f('uq_plugin_name'))
    )
    op.create_table('plugin_config',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', app.database.types.JSON(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], name=op.f('fk_plugin_config_plugin_id_plugin'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_config')),
    sa.UniqueConstraint('plugin_id', 'key', name='uq_plugin_config_key')
    )
    op.create_index(op.f('ix_plugin_config_plugin_id'), 'plugin_config', ['plugin_id'], unique=False)
    op.create_table('plugin_dependency',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_name', sa.String(length=100), nullable=False),
    sa.Column('version_spec', sa.String(length=50), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], name=op.f('fk_plugin_dependency_plugin_id_plugin'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_dependency')),
    sa.UniqueConstraint('plugin_id', 'dependency_name', name='uq_plugin_dependency_name')
    )
    op.create_index(op.f('ix_plugin_dependency_plugin_id'), 'plugin_dependency', ['plugin_id'], unique=False)
    op.create_table('plugin_limit',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('soft_limit', sa.String(length=50), nullable=True),
    sa.Column('hard_limit', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], name=op.f('fk_plugin_limit_plugin_id_plugin'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_limit')),
    sa.UniqueConstraint('plugin_id', 'resource_type', name='uq_plugin_limit_resource')
    )
    op.create_index(op.f('ix_plugin_limit_plugin_id'), 'plugin_limit', ['plugin_id'], unique=False)
    op.create_table('plugin_permission',
    sa.Column('id', app.database.types.AutoUUID(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], name=op.f('fk_plugin_permission_plugin_id_plugin'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_permission')),
    sa.UniqueConstraint('plugin_id', 'permission', name='uq_plugin_permission')
    )
    op.create_index(op.f('ix_plugin_permission_plugin_id'), 'plugin_permission', ['plugin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_permission_plugin_id'), table_name='plugin_permission')
    op.drop_table('plugin_permission')
    op.drop_index(op.f('ix_plugin_limit_plugin_id'), table_name='plugin_limit')
    op.drop_table('plugin_limit')
    op.drop_index(op.f('ix_plugin_dependency_plugin_id'), table_name='plugin_dependency')
    op.drop_table('plugin_dependency')
    op.drop_index(op.f('ix_plugin_config_plugin_id'), table_name='plugin_config')
    op.drop_table('plugin_config')
    op.drop_table('plugin')
    # ### end Alembic commands ###
