"""add plugin capabilities and core version constraints

Revision ID: 441be2989308
Revises: 8f8b9ac4ea3b
Create Date: 2026-07-02 19:04:54.318930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types  # noqa: F401 — used by autogenerate for custom types


# revision identifiers, used by Alembic.
revision: str = '441be2989308'
down_revision: Union[str, Sequence[str], None] = '8f8b9ac4ea3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('capabilities', app.database.types.JSON(), nullable=False))
    op.add_column('plugin', sa.Column('minimum_core_version', sa.String(length=30), nullable=True))
    op.add_column('plugin', sa.Column('maximum_core_version', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'maximum_core_version')
    op.drop_column('plugin', 'minimum_core_version')
    op.drop_column('plugin', 'capabilities')
    # ### end Alembic commands ###
